dabaojian/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin', admin.site.urls),
    path('api/', include('apps.api.urls')),
    path('web/', include('apps.web.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/api/models.py
from django.db import models

# Create your models here.

class UserInfo(models.Model):
    telephone = models.CharField(verbose_name='手机号', max_length=11)
    nickname = models.CharField(verbose_name='昵称', max_length=64)
    avatar = models.CharField(verbose_name='头像', max_length=64, null=True, blank=True)
    token = models.CharField(verbose_name='用户token', max_length=64, null=True, blank=True)
    balance = models.PositiveIntegerField(verbose_name='余额',default=1000)
    
class Topic(models.Model):
    """
    话题
    """
    title = models.CharField(verbose_name='话题', max_length=32)
    count = models.PositiveIntegerField(verbose_name='关注度', default=0)

class News(models.Model):
    """
    动态
    """
    cover = models.CharField(verbose_name='封面', max_length=128)
    content = models.CharField(verbose_name='内容', max_length=255)
    topic = models.ForeignKey(verbose_name='话题', to='Topic', null=True, blank=True, on_delete=models.SET_NULL) # 删除设为空
    user = models.ForeignKey(verbose_name='发布者', to='UserInfo', null=True, blank=True, related_name='news', on_delete=models.SET_NULL) # 当UserInfo中的user查询News模型的实例时可以反向关联的对象
    address = models.CharField(verbose_name='位置', max_length=128, null=True, blank=True)
    favor_count = models.PositiveIntegerField(verbose_name='赞数', default=0)
    viewer_count = models.PositiveIntegerField(verbose_name='浏览数', default=0)
    comment_count = models.PositiveIntegerField(verbose_name='评论数', default=0)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

class NewsDetail(models.Model):
    key = models.CharField(verbose_name='cos中的文件名', max_length=128, help_text='用于删除')
    cos_path = models.CharField(verbose_name='cos中的文件路径', max_length=128)
    news = models.ForeignKey(verbose_name='动态', to='News', on_delete=models.CASCADE)

class ViewerRecord(models.Model):
    news = models.ForeignKey(verbose_name='动态', to='News', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='用户', to='UserInfo', null=True, on_delete=models.SET_NULL)

class NewsFavorRecord(models.Model):
    """动态被赞的记录表"""
    news = models.ForeignKey(verbose_name='动态', to='News', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='点赞用户', to='UserInfo', null=True, on_delete=models.SET_NULL)

class CommentRecord(models.Model):
    news = models.ForeignKey(verbose_name='动态', to='News', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', on_delete=models.CASCADE)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_date = models.DateTimeField(verbose_name='评论时间', auto_now_add=True)
    reply = models.ForeignKey(verbose_name='回复', to='self', null=True, blank=True, on_delete=models.SET_NULL)
    depth = models.PositiveIntegerField(verbose_name='评论层级', default=1)
    root = models.ForeignKey(verbose_name='根评论', to='self', null=True, blank=True, related_name='comment_root', on_delete=models.CASCADE)
    favor_count = models.PositiveIntegerField(verbose_name='赞数', default=0)

class CommentFavorRecord(models.Model):
    """
    评论赞记录
    """
    comment = models.ForeignKey(verbose_name='动态', to='CommentRecord', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='点赞用户', to='UserInfo', on_delete=models.CASCADE)


### 开始拍卖内容 ###
class Auction(models.Model):
    """拍卖专场"""
    status_choices = (
        (1, '未开拍'),
        (2, '预展中'),
        (3, '拍卖中'),
        (4, '已结束')
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices, default=1)
    title = models.CharField(verbose_name='标题', max_length=32)
    # 改为FileField = 数据库保存文件路径CharField + ModelForm显示时File来生成标签，在modelform.save时默认会保存到本地
    cover = models.FileField(verbose_name='封面', max_length=128)
    video = models.CharField(verbose_name='预览视频', max_length=128, null=True, blank=True)

    preview_start_time = models.DateTimeField(verbose_name='预展开始时间')
    preview_end_time = models.DateTimeField(verbose_name='预展结束时间')

    auction_start_time = models.DateTimeField(verbose_name='拍卖开始时间')
    auction_end_time = models.DateTimeField(verbose_name='拍卖结束时间')

    deposit = models.PositiveIntegerField(verbose_name='全场保证金', default=1000)

    total_price = models.PositiveIntegerField(verbose_name='成交额', null=True, blank=True)
    goods_count = models.PositiveIntegerField(verbose_name='拍品数量', default=0)
    bid_count = models.PositiveIntegerField(verbose_name='出价次数', default=0)
    look_count = models.PositiveIntegerField(verbose_name='围观次数', default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    class Meta:
        verbose_name_plural = '拍卖系列'
    def __str__(self):
        return self.title
    
class AuctionTask(models.Model):
    """定时任务"""
    auction = models.OneToOneField(verbose_name='专场', to='Auction', on_delete=models.CASCADE) # 和auction是一一对应的，所以也可以写在auction中，不过这样拆分后结构更清晰
    preview_task = models.CharField(verbose_name='Celery预展任务ID', max_length=64)
    auction_task = models.CharField(verbose_name='Celery拍卖任务ID', max_length=64)
    auction_end_task = models.CharField(verbose_name='Celery拍卖结束任务ID', max_length=64)

class AuctionItem(models.Model):
    """
    拍卖商品
    """
    auction = models.ForeignKey(verbose_name='拍卖专场', to='Auction', null=True, on_delete=models.SET_NULL)
    uid = models.CharField(verbose_name='图录号', max_length=12)

    status_choices = (
        (1, '待拍卖'),
        (2, '预展中'),
        (3, '拍卖中'),
        (4, '成交'),
        (5, '流拍'),
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices, default=1)
    title = models.CharField(verbose_name='拍品名称', max_length=32)
    cover = models.FileField(verbose_name='拍品封面', max_length=128)

    start_price = models.PositiveIntegerField(verbose_name='起拍价')
    deal_price = models.PositiveIntegerField(verbose_name='成交价', null=True, blank=True)

    reserve_price = models.PositiveIntegerField(verbose_name='参考底价')
    highest_price = models.PositiveIntegerField(verbose_name='参考高价')

    video = models.CharField(verbose_name='预览视频', max_length=128, null=True, blank=True)
    deposit = models.PositiveIntegerField(verbose_name='单品保证金', default=100)
    unit = models.PositiveIntegerField(verbose_name='加价幅度', default=100)

    bid_count = models.PositiveIntegerField(verbose_name='出价次数', default=0)
    look_count = models.PositiveIntegerField(verbose_name='围观次数', default=0)

    class Meta:
        verbose_name_plural = '拍品'

    def __str__(self):
        return self.title
    
class AuctionItemImage(models.Model):
    """
    拍品相关图片
    """
    item = models.ForeignKey(verbose_name='拍品', to='AuctionItem', on_delete=models.CASCADE)
    img = models.FileField(verbose_name='详细图', max_length=64)
    carousel = models.BooleanField(verbose_name='是否在轮播中显示', default=False)
    order = models.FloatField(verbose_name="排序", default=1)

    class Meta:
        verbose_name_plural = '拍品详细图'

    def __str__(self):
        return "{}-{}".format(self.item.title, self.id, )
    
class AuctionItemDetail(models.Model):
    """
    拍品详细规格
    """
    item = models.ForeignKey(verbose_name='拍品', to='AuctionItem', on_delete=models.CASCADE)
    key = models.CharField(verbose_name='项', max_length=16)
    value = models.CharField(verbose_name='值', max_length=32)

    class Meta:
        verbose_name_plural = '拍品规格'

class BrowseRecord(models.Model):
    """
    浏览记录
    """
    item = models.ForeignKey(verbose_name='拍品', to='AuctionItem', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='用户', to='UserInfo', on_delete=models.CASCADE)

class BidRecord(models.Model):
    """
    出价记录
    """
    status_choices = (
        (1, '竞价'),
        (2, '成交'),
        (3, '逾期未付款'),
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices, default=1)
    item = models.ForeignKey(verbose_name='拍品', to='AuctionItem', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='出价人', to='UserInfo', on_delete=models.CASCADE)
    price = models.PositiveIntegerField(verbose_name='出价')

class DepositRecord(models.Model):
    """ 保证金 """
    status_choices = (
        (1, '未支付'),
        (2, '支付成功')
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices, default=1)

    uid = models.CharField(verbose_name='流水号', max_length=64)
    deposit_type_choices = (
        (1, '单品保证金'),
        (2, '全场保证金')
    )
    deposit_type = models.SmallIntegerField(verbose_name='保证金类型', choices=deposit_type_choices)
    pay_type_choices = (
        (1, '微信'),
        (2, '余额')
    )
    pay_type = models.SmallIntegerField(verbose_name='支付方式', choices=pay_type_choices)

    amount = models.PositiveIntegerField(verbose_name='金额')

    user = models.ForeignKey(verbose_name='用户', to='UserInfo', on_delete=models.CASCADE)

    # 单品保证金则设置值，全场保证金，则为空
    item = models.ForeignKey(verbose_name='拍品', to='AuctionItem', null=True, blank=True, on_delete=models.SET_NULL)
    auction = models.ForeignKey(verbose_name='拍卖专场', to='Auction', null=True, on_delete=models.SET_NULL)

class Order(models.Model):
    """拍卖结束时执行定时任务
        - 拍得，创建订单
        - 未拍得，退款到原账户
    """
    status_choices = (
        (1, '未支付'),
        (2, '待收货'),
        (3, '已完成'),
        (4, '逾期未支付'),
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices)

    uid = models.CharField(verbose_name='流水号', max_length=64)
    user = models.ForeignKey(verbose_name='用户', to='UserInfo', null=True, on_delete=models.SET_NULL)
    item = models.ForeignKey(verbose_name='拍品', to='AuctionItem', null=True, on_delete=models.SET_NULL)
    deposit = models.ForeignKey(verbose_name='保证金', to='DepositRecord', null=True, on_delete=models.SET_NULL)
    price = models.PositiveIntegerField(verbose_name='出价')
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

apps/api/views/coupon.py
from django.db import transaction
from rest_framework import exceptions, serializers, status
from rest_framework.generics import ListAPIView, CreateAPIView
from collections import OrderedDict
from utils.auth import UserAuthentication, GeneralAuthentication
from apps.api import models

class CouponModelSerializer(serializers.ModelSerializer):
    apply_start_date = serializers.DateTimeField(format='%Y-%m-%d %H:%M:%S')
    apply_stop_date = serializers.DateTimeField(format='%Y-%m-%d %H:%M:%S')
    status_text = serializers.CharField(source='get_status_display')
    cover = serializers.CharField(source='auction.cover')
    remain = serializers.SerializerMethodField()
    class Meta:
        model = models.Coupon
        exclude = ['apply_start_task_id', 'apply_stop_task_id', 'deleted', 'count']
    
    def get_remain(self, obj):
        return obj.count - obj.apply_count
    
class CouponView(ListAPIView):
    queryset = models.Coupon.objects.filter(deleted=False).exclude(status=1).order_by('-id')
    serializer_class = CouponModelSerializer

# 用户领用优惠券
class UserCouponModelSerializer(serializers.ModelSerializer):
    remain = serializers.SerializerMethodField()
    class Meta:
        model = models.UserCoupon
        fields = ['remain', 'coupon']
    def get_remain(self, obj):
        return obj.coupon.count-obj.coupon.apply_count
    
    def validate_coupon(self, value): # 对post提交的数据进行验证
        user_object = self.context['request'].user
        if not value or value.deleted:
            raise exceptions.ValidationError('优惠券不存在')
        if value.status != 2:
            raise exceptions.ValidationError('优惠券不可领取')
        # 优惠券个数是否合法
        if (value.apply_count + 1) > value.count:
            raise exceptions.ValidationError('优惠券已领完')
        # 是否已领取优惠券
        exists = models.UserCoupon.objects.filter(user=user_object, coupon=value).exists()
        if exists:
            raise exceptions.ValidationError('已领取此优惠券')
        return value

class MyUserCouponModelSerializer(serializers.ModelSerializer):
    status_text = serializers.CharField(source='get_status_display')
    coupon = serializers.CharField(source='coupon.title')
    cover = serializers.CharField(source='coupon.auction.cover')
    money = serializers.CharField(source='coupon.money')

    class Meta:
        model = models.UserCoupon
        fields = "__all__"

class UserCouponView(ListAPIView, CreateAPIView):
    # authentication_classes = [UserAuthentication, ]
    authentication_classes = [GeneralAuthentication, ]

    def get_serializer_class(self):
        if self.request.method == 'POST':
            return UserCouponModelSerializer
        return MyUserCouponModelSerializer

    def perform_create(self, serializer):
        # post请求过来 事务+锁
        with transaction.atomic():
            coupon_object = models.Coupon.objects.filter(id=serializer.validated_data['coupon'].id).select_for_update().first()
            if (coupon_object.apply_count + 1) > coupon_object.count:
                raise exceptions.ValidationError('优惠券已领完')
            serializer.save(user=self.request.user)
            coupon_object.apply_count += 1
            coupon_object.save() # 这是存到数据库中
    
    def get_queryset(self):
        # 只能取当前用户的优惠券 所以要用这个函数
        return models.UserCoupon.objects.filter(user=self.request.user)

    def list(self, *args, **kwargs):
        response = super().list(*args, **kwargs)
        if response.status_code != status.HTTP_200_OK:
            return response
        """
        {
            1:{text:'未使用',child:[..]}
            2:{text:'已使用',child:[...]}
            3:{text:'已过期',child:[...]}
        }
        """
        status_dict = OrderedDict()
        for item in models.UserCoupon.status_choices:
            status_dict[item[0]] = {'text': item[1], 'child': []}
        for row in response.data: # 已经序列化成json data了
            status_dict[row['status']]['child'].append(row)
        response.data = status_dict
        return response
    
class ChooseCouponModelSerializer(serializers.ModelSerializer):
    title = serializers.CharField(source='coupon.title')
    cover = serializers.CharField(source='coupon.auction.cover')
    money = serializers.CharField(source='coupon.money')

    class Meta:
        model = models.UserCoupon
        fields = ['id', 'title', 'money', 'cover']
        
class ChooseCouponView(ListAPIView):
    """ 支付页面 选择优惠券 """
    authentication_classes = [UserAuthentication, ]
    serializer_class = ChooseCouponModelSerializer

    def get_queryset(self):
        auction = self.request.query_params.get('auction')
        # return models.UserCoupon.objects.filter(user=self.request.user, coupon__auction_id=auction, status=1)
        return models.UserCoupon.objects.all()

apps/web/templates/web/auction_form.html
{% extends 'web/layout.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'web/datetimepicker/bootstrap-datetimepicker.min.css' %}">
    <style>
        input[type='file'] {
            min-height: 34px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <form method="post" novalidate enctype="multipart/form-data">
            {% csrf_token %}
            <div class="panel panel-default">
                <div class="panel-heading clearfix">拍卖专场
                    <input type="submit" class="btn btn-success btn-xs" value="保 存" style="float: right;">
                </div>
                <div class="panel-body">
                    <div class="form-horizontal clearfix">
                        {% for field in form %}
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}"
                                           class="col-sm-3 control-label">{{ field.label }}</label>
                                    <div class="col-sm-9">
                                        {{ field }}
                                        <span style="color: red;">{{ field.errors.0 }}</span>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'web/datetimepicker/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'web/datetimepicker/bootstrap-datetimepicker.zh-CN.js' %}"></script>
    <script>
        Date.prototype.Format = function (fmt) { //author: meizz
            var o = {
                "M+": this.getMonth() + 1, //月份
                "d+": this.getDate(), //日
                "h+": this.getHours(), //小时
                "m+": this.getMinutes(), //分
                "s+": this.getSeconds(), //秒
                "q+": Math.floor((this.getMonth() + 3) / 3), //季度
                "S": this.getMilliseconds() //毫秒
            };
            if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
            for (var k in o)
                if (new RegExp("(" + k + ")").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
            return fmt;
        };

        $(function () {
            initDatepicker();
        });

        function initDatepicker() {
            $('#id_preview_start_time,#id_preview_end_time,#id_auction_start_time,#id_auction_end_time').datetimepicker({
                language: "zh-CN",
                minView: "hour", // month
                sideBySide: true,
                format: 'yyyy-mm-dd hh:ii',
                bootcssVer: 3,
                startDate: new Date(),
                autoclose: true
            })
        }
    </script>

{% endblock %}

apps/web/templates/web/auction_item_add.html
{% extends 'web/layout.html' %}
{% load static %}
{% block css %}
    <style>
        input[type='file'] {
            min-height: 34px;
        }

        .file-view {
            height: 80px;
            width: 80px;
            padding: 2px;
            border: 1px dotted #dddddd;
            position: relative;
        }

        .file-view .view-file {
            position: absolute;
            width: 100%;
            height: 100%;
            opacity: 0;
            z-index: 1001
        }

        .file-view .view-img {
            height: 100%;
            width: 100%;
            border: 0;
            overflow: hidden;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .field-error {
            color: red;
            position: absolute;
            font-size: 12px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid">

        <div class="panel panel-default">
            <div class="panel-heading clearfix">{{ auction_object.title }} - 创建拍品
                <a class="btn btn-primary btn-xs" style="float: right;" id="btnSave">
                    <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> 保 存
                </a>
            </div>
            <div class="panel-body">
                <div class="form-horizontal clearfix">
                    <form id="itemForm">
                        {% for field in form %}
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}"
                                           class="col-sm-3 control-label">{{ field.label }}</label>
                                    <div class="col-sm-9" style="position: relative;">
                                        {{ field }}
                                        <span class="field-error">{{ field.errors.0 }}</span>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </form>

                </div>
                <hr/>
                <div class="clearfix">
                    <div class="col-sm-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">拍品规格</div>
                            <div class="panel-body">
                                <div class="form-inline">
                                    <div class="form-group" style="position: relative;">
                                        <input type="text" class="form-control input-sm" placeholder="项" id="key">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control input-sm" placeholder="值" id="value">
                                    </div>
                                    <a class="btn btn-success btn-sm" id="btnAddSpecification">
                                        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 添 加
                                    </a>
                                </div>
                            </div>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>项</th>
                                    <th>对应值</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody id="areaSpecification">

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">拍品详细图片</div>
                            <div class="panel-body">

                                <a class="btn btn-success btn-sm" id="btnAddImage">
                                    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> 添 加
                                </a>
                                <div id="imageTemplate" style="display: none;">
                                    <table>
                                        <tr>
                                            <td>
                                                <div class="file-view">
                                                    <input class="view-file" type="file" name="img">
                                                    <img class="view-img"
                                                         src="{% static 'web/images/default-image.png' %}">
                                                </div>
                                            </td>
                                            <td>
                                                <input type="checkbox">
                                                <input type="text" name="show" hidden>
                                            </td>
                                            <td>
                                                <a class="btn btn-danger btn-xs delete">删除</a>
                                            </td>
                                        </tr>
                                    </table>
                                </div>

                            </div>
                            <form id="imageForm">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>图片</th>
                                        <th>是否轮播</th>
                                        <th>操作</th>
                                    </tr>
                                    </thead>
                                    <tbody id="areaImage">


                                    </tbody>
                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="loading" class="loading hide">
        <div class="loading-icon">
            <img src="{% static 'web/images/loading.gif' %}" alt="">
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        SUB_HANDLE_COUNT = 0;

        $(function () {
            bindChangeImageFile();

            bindAddSpecification();
            bindDeleteSpecification();

            bindAddDetailImage();
            bindDeleteDetailImage();
            bindImageCheckBox();
            bindSave();
        });

        /**
         * 图片预览
         */
        function bindChangeImageFile() {
            $('#areaImage').on('change', '.view-file', function () {
                var fileObject = $(this)[0].files[0];
                var blob = window.URL.createObjectURL(fileObject);
                $(this).next().attr('src', blob);
                $(this).next().load(function () {
                    window.URL.revokeObjectURL(blob);
                })
            })
        }

        /**
         * 添加规格
         */
        function bindAddSpecification() {
            $('#btnAddSpecification').click(function () {
                var info = {
                    "key": $('#key'),
                    "value": $('#value')
                };
                var tr = $('<tr>');
                for (var k in info) {
                    info[k].parent().removeClass('has-error');
                    var value = info[k].val();
                    if (value.trim().length < 1) {
                        info[k].parent().addClass('has-error');
                        return
                    }
                    tr.append($('<td>').text(value).attr('name', k));
                }
                tr.append($("<td>").html('<a class="btn btn-danger btn-xs delete">删除</a>'));
                $("#areaSpecification").append(tr);

                for (var item in info) {
                    info[item].val('');
                }

            })
        }

        /**
         * 删除规格
         */
        function bindDeleteSpecification() {
            $('#areaSpecification').on('click', '.delete', function () {
                $(this).parent().parent().remove();
            })
        }

        /**
         * 添加图片详细
         */
        function bindAddDetailImage() {
            $('#btnAddImage').click(function () {
                $('#imageTemplate tr').clone().appendTo("#areaImage");
            });
        }

        /**
         * 删除图片详细
         */
        function bindDeleteDetailImage() {
            $('#areaImage').on('click', '.delete', function () {
                $(this).parent().parent().remove();
            })
        }

        /**
         * 保存
         */
        function bindSave() {
            $('#btnSave').click(function () {
                $('.field-error').text("");

                // 加载层
                $('#loading').removeClass('hide');
                SUB_HANDLE_COUNT = 0;
                var itemFormData = new FormData($('#itemForm')[0]);
                $.ajax({
                    type: 'POST',
                    url: '{% url "auction_item_add" auction_id=auction_object.id %}',
                    data: itemFormData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    dataType: 'JSON',
                    success: function (res) {
                        if (!res.status) {
                            $('#loading').addClass('hide');
                            $.each(res.errors, function (key, text) {
                                $('#itemForm').find('[name="' + key + '"]').next().text(text);
                            });
                            return
                        }
                        // 创建规格
                        createSpecification(res.data.detail_url, res.data.list_url);
                        // 创建图片
                        createImage(res.data.image_url, res.data.list_url);
                    }
                })
            });
        }

        /**
         * 创建规则
         */
        function createSpecification(url, listUrl) {
            var dataList = [];
            $('#areaSpecification').children().each(function () {
                var info = {};
                $(this).children().each(function () {
                    var name = $(this).attr('name');
                    if (name) {
                        info[name] = $(this).text();
                    }
                });
                dataList.push(info);
            });
            $.ajax({
                url: url,
                type: "POST",
                data: JSON.stringify(dataList),
                dataType: "JSON",
                success: function (res) {
                    ending(res, listUrl);
                }
            })
        }

        /**
         * 创建图片详细
         */
        function createImage(url, listUrl) {
            var imageForm = new FormData($('#imageForm')[0]);
            console.log(imageForm);
            $.ajax({
                url: url,
                type: "POST",
                data: imageForm,
                cache: false,
                contentType: false,
                processData: false,
                dataType: "JSON",
                success: function (res) {
                    ending(res, listUrl);
                }
            })
        }


        /**
         * 绑定修改checkbox
         */
        function bindImageCheckBox() {
            $("#imageForm").on('click', ':checkbox', function () {
                if ($(this).prop('checked')) {
                    $(this).next().val('1');
                } else {
                    $(this).next().val('');
                }
            });
        }

        function ending(res, listUrl) {
            SUB_HANDLE_COUNT += 1;
            if (SUB_HANDLE_COUNT === 2) {
                location.href = listUrl;
            }
        }
    </script>
{% endblock %}